version: "3.1"

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myUserPass
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./MySql:/docker-entrypoint-initdb.d/:ro

  # Backend
  testproject:
    container_name: backend
    build: ./
    volumes:
      - ./:/usr/src/testproject
    command: yarn dev
    working_dir: /usr/src/testproject
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    links:
      - mysql
